CREATE TABLE IF NOT EXISTS USERS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS SATELLITES (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    function VARCHAR(100) NOT NULL,
    status VARCHAR(50) DEFAULT 'Operational',
    risk_level VARCHAR(20) DEFAULT 'Low'
);

CREATE TABLE IF NOT EXISTS SECURITY_EVENTS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    satellite_id INT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    description TEXT,
    event_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (satellite_id) REFERENCES SATELLITES(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SECURITY_ALERTS (
    id INT PRIMARY KEY AUTO_INCREMENT,
    event_id INT NOT NULL,
    severity VARCHAR(20) NOT NULL,
    resolution_status VARCHAR(50) DEFAULT 'Active',
    FOREIGN KEY (event_id) REFERENCES SECURITY_EVENTS(id) ON DELETE CASCADE
);
